const formats=["JPG","PNG","WEBP","GIF","BMP","TIFF","SVG","AVIF","ICO","HEIC","JSON","CSV","TSV","XML","YAML","TXT","MD","HTML","WAV","MP3","OGG","M4A","MP4","WEBM","MOV"];
const popular=[["HEIC","JPG","Convert HEIC photos to widely supported JPG images."],["WEBP","JPG","Turn modern web images into JPG files for broader compatibility."],["PNG","WEBP","Reduce image size for the web."],["JPG","PNG","Convert JPG images to lossless PNG."],["SVG","PNG","Rasterize vector artwork into PNG."],["JSON","CSV","Turn structured JSON data into spreadsheet-ready CSV."],["CSV","JSON","Convert tabular CSV data into structured JSON."],["XML","JSON","Convert XML data into JSON."],["YAML","JSON","Convert YAML configuration data into JSON."],["TSV","CSV","Convert tab-separated data into CSV."]];
let from=null,to=null;
const fromBtn=document.querySelector("#fromFormat"),toBtn=document.querySelector("#toFormat"),fromMenu=document.querySelector("#fromMenu"),toMenu=document.querySelector("#toMenu"),fileInput=document.querySelector("#fileInput"),selectFile=document.querySelector("#selectFile"),status=document.querySelector("#status"),dropzone=document.querySelector("#dropzone");
function buildMenu(menu,btn,setter){menu.innerHTML=formats.map(function(f){return '<button type="button" data-format="'+f+'">'+f+"</button>"}).join("");menu.addEventListener("click",function(e){const b=e.target.closest("button");if(!b)return;setter(b.dataset.format);menu.classList.remove("open")});btn.addEventListener("click",function(){fromMenu.classList.remove("open");toMenu.classList.remove("open");menu.classList.toggle("open")})}
buildMenu(fromMenu,fromBtn,function(f){from=f;fromBtn.innerHTML=f+" <span>⌄</span>";refresh()});
buildMenu(toMenu,toBtn,function(f){to=f;toBtn.innerHTML=f+" <span>⌄</span>";refresh()});
document.addEventListener("click",function(e){if(!e.target.closest(".format-pick")){fromMenu.classList.remove("open");toMenu.classList.remove("open")}});
function refresh(){selectFile.disabled=!(from&&to&&from!==to);status.textContent=from&&to&&from!==to?from+" → "+to+" is ready. Choose a file to begin.":from===to&&from?"Choose two different formats.":""}
selectFile.addEventListener("click",function(){fileInput.click()});
dropzone.addEventListener("click",function(){if(!selectFile.disabled)fileInput.click()});
dropzone.addEventListener("dragover",function(e){e.preventDefault();dropzone.style.borderColor="var(--accent)"});
dropzone.addEventListener("dragleave",function(){dropzone.style.borderColor=""});
dropzone.addEventListener("drop",function(e){e.preventDefault();dropzone.style.borderColor="";if(!selectFile.disabled&&e.dataTransfer.files[0])convert(e.dataTransfer.files[0])});
fileInput.addEventListener("change",function(e){if(e.target.files[0])convert(e.target.files[0])});
function download(blob,name){const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(function(){URL.revokeObjectURL(a.href)},1000)}
function imageConvert(file,target){const img=new Image();img.onload=function(){const c=document.createElement("canvas");c.width=img.naturalWidth;c.height=img.naturalHeight;const x=c.getContext("2d");if(target==="JPG"){x.fillStyle="#fff";x.fillRect(0,0,c.width,c.height)}x.drawImage(img,0,0);const mime=target==="PNG"?"image/png":target==="WEBP"?"image/webp":"image/jpeg";c.toBlob(function(blob){if(!blob){status.textContent="This browser could not encode that format.";return}download(blob,file.name.replace(/\.[^.]+$/,"")+"."+target.toLowerCase());status.textContent="Done — converted "+file.name+" to "+target+"."},mime,.92)};img.onerror=function(){status.textContent="This image format cannot be decoded by this browser."};img.src=URL.createObjectURL(file)}
function jsonToCsv(file){const r=new FileReader();r.onload=function(){try{const data=JSON.parse(r.result);const rows=Array.isArray(data)?data:[data];const keys=[];rows.forEach(function(o){Object.keys(o||{}).forEach(function(k){if(keys.indexOf(k)<0)keys.push(k)})});function esc(v){return '"'+String(v==null?"":v).replace(/"/g,'""')+'"'}const csv=[keys.map(esc).join(","),...rows.map(function(o){return keys.map(function(k){return esc(typeof o[k]==="object"?JSON.stringify(o[k]):o[k])}).join(",")})].join("\n");download(new Blob([csv],{type:"text/csv"}),file.name.replace(/\.[^.]+$/,"")+".csv");status.textContent="Done — JSON converted to CSV."}catch(e){status.textContent="Invalid JSON file."}};r.readAsText(file)}
function csvToJson(file){const r=new FileReader();r.onload=function(){const lines=r.result.replace(/^\uFEFF/,"").trim().split(/\r?\n/);if(lines.length<2){status.textContent="CSV needs a header row and at least one data row.";return}function split(s){return s.split(",").map(function(v){return v.trim().replace(/^"(.*)"$/,"$1").replace(/""/g,'"')})}const headers=split(lines[0]);const data=lines.slice(1).map(function(line){const values=split(line);const row={};headers.forEach(function(h,i){row[h]=values[i]||""});return row});download(new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),file.name.replace(/\.[^.]+$/,"")+".json");status.textContent="Done — CSV converted to JSON."};r.readAsText(file)}
function convert(file){status.textContent="Working…";const imageIn=["JPG","JPEG","PNG","WEBP","GIF","BMP"].indexOf(from)>=0;const imageOut=["JPG","PNG","WEBP"].indexOf(to)>=0;if(imageIn&&imageOut){imageConvert(file,to);return}if(from==="JSON"&&to==="CSV"){jsonToCsv(file);return}if(from==="CSV"&&to==="JSON"){csvToJson(file);return}status.textContent=from+" → "+to+" is queued for the next engine pack. This route is not falsely advertised as working yet."}
document.querySelector("#popularGrid").innerHTML=popular.map(function(item){return '<a class="tool-card" href="#converter" onclick="pick(\''+item[0]+'\',\''+item[1]+'\')"><div class="tool-icon">'+item[0]+" → "+item[1]+"</div><h3>"+item[0]+" to "+item[1]+"</h3><p>"+item[2]+"</p></a>"}).join("");
window.pick=function(a,b){from=a;to=b;fromBtn.innerHTML=a+" <span>⌄</span>";toBtn.innerHTML=b+" <span>⌄</span>";refresh();document.querySelector("#converter").scrollIntoView({behavior:"smooth"})};
document.querySelector("#formatGrid").innerHTML=formats.map(function(f){return '<div class="format-pill"><b>'+f+"</b></div>"}).join("");
